package warehouse_test;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import addType.*;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
//import javax.persistence.Table;
import javax.swing.JComboBox;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import page.exportProduct;
import page.importProduct;
import page.searchPage;

/**
 *
 * @author User
 */
public class WareHouse_Test extends javax.swing.JFrame {


    DefaultTableModel dm = new DefaultTableModel();
    DefaultTableModel d = new DefaultTableModel();

    /**
     * Creates new form WareHouse_Test
     */
    public WareHouse_Test() {
        initComponents();

        Sql s = new Sql();

        s.Select_MaterialItem(Materials_combox);
        s.loadcombo(item_combox);
        s.Select_BigItem(Bigitem_combox);
        //jLabel17.setText(jSpinner2.getValue().toString());
        System.out.println(in_time_spin.getValue());
        dm.addColumn("編號");
        dm.addColumn("進貨");
        dm.addColumn("出貨");
        dm.addColumn("金額");
        dm.addColumn("數量");
        dm.addColumn("單位");
        dm.addColumn("時間");
        dm.addColumn("部門");
        dm.addColumn("廠商");
        this.setTitle("WareHouse");

    }

    public DefaultTableModel getdata() {
        GetData getdata = new GetData();
        getdata.getData(dm);
        return dm;
    }

    public String getCellValue(int x, int y) {
        return dm.getValueAt(x, y).toString();
    }

    private void writeExcel() throws IOException {
        Excel wd = new Excel();
        wd.Write();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jSpinner1 = new javax.swing.JSpinner();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        Label2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        in_total_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Materials_combox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        department_combox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        company_TFile = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        in_quantity_TFile = new javax.swing.JTextField();
        out_quantity_TFile = new javax.swing.JTextField();
        in_type_combox = new javax.swing.JComboBox<>();
        out_type_combox = new javax.swing.JComboBox<>();
        out_time_spin = new javax.swing.JSpinner();
        Bigitem_combox = new javax.swing.JComboBox<>();
        item_combox = new javax.swing.JComboBox<>();
        out_total_btn = new javax.swing.JButton();
        test = new javax.swing.JLabel();
        money_TFile = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        recycle_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        outputExcel_btn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        in_time_spin = new javax.swing.JSpinner();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Menu = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        menu_addLargeProject = new javax.swing.JMenuItem();
        menu_addItem = new javax.swing.JMenuItem();
        menu_addMaterial = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar4.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("進貨金額：");

        in_total_btn.setText("進　貨");
        in_total_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in_total_btnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("大項目：");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("分　類：");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("物　料:");

        jLabel11.setText("進貨日期時間：");

        jLabel12.setText("出貨日期時間：");

        department_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. 吧檯", "2. 外場", "3. 廚房", "4. 甜點" }));

        jLabel13.setText("部　門：");

        jLabel14.setText("廠　商：");

        jLabel15.setText("進貨數量：");

        jLabel16.setText("出貨數量：");

        in_type_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "箱", "盒", "個", "公斤", "斤", "公克" }));

        out_type_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "箱", "盒", "個", "公斤", "斤", "公克" }));

        out_time_spin.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));

        Bigitem_combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bigitem_comboxActionPerformed(evt);
            }
        });

        item_combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_comboxActionPerformed(evt);
            }
        });

        out_total_btn.setText("出　貨");
        out_total_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                out_total_btnActionPerformed(evt);
            }
        });

        test.setText("jLabel17");

        search_btn.setText("查　詢");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "編號", "進貨", "出貨", "金額", "數量", "單位", "時間", "部門", "廠商"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        recycle_btn.setText("重　整");
        recycle_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recycle_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        outputExcel_btn.setText("匯    出");
        outputExcel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputExcel_btnActionPerformed(evt);
            }
        });

        jButton2.setText("清除本月資料");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        in_time_spin.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));

        jMenu8.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem1);

        jMenuBar2.add(jMenu8);

        Menu.setText("Edit");

        jMenu9.setText("addType");

        menu_addLargeProject.setText("addLargeProject");
        menu_addLargeProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_addLargeProjectActionPerformed(evt);
            }
        });
        jMenu9.add(menu_addLargeProject);

        menu_addItem.setText("addItem");
        menu_addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_addItemActionPerformed(evt);
            }
        });
        jMenu9.add(menu_addItem);

        menu_addMaterial.setText("addMaterial");
        menu_addMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_addMaterialActionPerformed(evt);
            }
        });
        jMenu9.add(menu_addMaterial);

        Menu.add(jMenu9);

        jMenuItem2.setText("testImport");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Menu.add(jMenuItem2);

        jMenuItem3.setText("testexport");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Menu.add(jMenuItem3);

        jMenuItem4.setText("testSearch");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Menu.add(jMenuItem4);

        jMenuItem5.setText("testHOME");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        Menu.add(jMenuItem5);

        jMenuBar2.add(Menu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(test)
                    .addGap(459, 459, 459))
                .addGroup(layout.createSequentialGroup()
                    .addGap(653, 653, 653)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(in_total_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(out_total_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(outputExcel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(89, 89, 89)
                            .addComponent(Label2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(recycle_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(Bigitem_combox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(item_combox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(Materials_combox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(money_TFile, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(out_quantity_TFile, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(out_type_combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(in_quantity_TFile, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(in_type_combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(company_TFile, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(department_combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(in_time_spin, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(out_time_spin, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(280, 280, 280))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(in_total_btn)
                            .addComponent(search_btn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(out_total_btn)
                            .addComponent(recycle_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(outputExcel_btn)
                            .addComponent(jButton2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Label2)
                        .addGap(105, 105, 105)))
                .addGap(12, 12, 12)
                .addComponent(test)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(Bigitem_combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(Materials_combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(in_time_spin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(out_time_spin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(money_TFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(in_quantity_TFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(in_type_combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(out_quantity_TFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(out_type_combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(department_combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(company_TFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(228, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item_comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_comboxActionPerformed
        // TODO add your handling code here:
        item_combox = (JComboBox<String>) evt.getSource();
        Object selected = item_combox.getSelectedIndex();
        String test = item_combox.getItemAt((int) selected);
        String result[] = test.split(".  ");

        System.out.println(result[0]);

        Sql s = new Sql();
        int type = Integer.valueOf(result[0]);

//        type++;

       s.SelectCheck_Material_type(Materials_combox, type);
        

    }//GEN-LAST:event_item_comboxActionPerformed

    private void Bigitem_comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bigitem_comboxActionPerformed
        // TODO add your handling code here:
        Bigitem_combox = (JComboBox<String>) evt.getSource();
        Object selected = Bigitem_combox.getSelectedIndex();
        String test = Bigitem_combox.getItemAt((int) selected);
        String result[] = test.split(".  ");
        
        
        
        Sql s = new Sql();
        int type = Integer.valueOf(result[0]);
//        type++;
//重點
//        s.SelectCheck_Item_type(item_combox, type);

    }//GEN-LAST:event_Bigitem_comboxActionPerformed

    private void in_total_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in_total_btnActionPerformed
        // TODO add your handling code here:
        try {

            String no = Materials_combox.getSelectedItem().toString();
            int money = Integer.parseInt(money_TFile.getText());
            int in_quantity = Integer.parseInt(in_quantity_TFile.getText());
            String in_type = in_type_combox.getSelectedItem().toString();
            String time = in_time_spin.getValue().toString();
            String department = department_combox.getSelectedItem().toString();
            String company = company_TFile.getText();

            Sql s = new Sql();
            s.insert_inTotal(no, money, in_quantity, in_type, time, department, company);

            //clear
            money_TFile.setText("");
            in_quantity_TFile.setText("");
            company_TFile.setText("");

            test.setText(no + " " + money + " " + in_quantity + " " + in_type + " " + time + " " + department + " " + company);

            //Search
            // TODO add your handling code here:
            //jTable1.invalidate();
            //jTable1.setModel(recycle());
            DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
            dm.getDataVector().removeAllElements();
            dm.fireTableDataChanged();
            jTable1.clearSelection();
            jTable1.setModel(getdata());

        } catch (NumberFormatException e) {

            JOptionPane.showConfirmDialog(null, "有資料未輸入！", "進貨錯誤",
                     JOptionPane.DEFAULT_OPTION,
                     JOptionPane.ERROR_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "有資料未輸入！", "進貨錯誤",
                     JOptionPane.DEFAULT_OPTION,
                     JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_in_total_btnActionPerformed

    private void out_total_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_out_total_btnActionPerformed
        // TODO add your handling code here:
        try {
            String no = Materials_combox.getSelectedItem().toString();
            //int money = Integer.parseInt(money_TFile.getText());
            int out_quantity = Integer.parseInt(out_quantity_TFile.getText());
            String out_type = out_type_combox.getSelectedItem().toString();
            String time = out_time_spin.getValue().toString();
            String department = department_combox.getSelectedItem().toString();
            String company = company_TFile.getText();

            Sql s = new Sql();
            s.insert_outTotal(no, out_quantity, out_type, time, department, company);
            test.setText(no + " " + out_quantity + " " + out_type + " " + time + " " + department + " " + company);

            //clear
            out_quantity_TFile.setText("");
            company_TFile.setText("");

            // TODO add your handling code here:
            //jTable1.invalidate();
            //jTable1.setModel(recycle());
            DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
            dm.getDataVector().removeAllElements();
            dm.fireTableDataChanged();
            jTable1.clearSelection();
            jTable1.setModel(getdata());
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null, "有資料未輸入！", "出貨錯誤",
                     JOptionPane.DEFAULT_OPTION,
                     JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "有資料未輸入！", "出貨錯誤",
                     JOptionPane.DEFAULT_OPTION,
                     JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_out_total_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        //jTable1.invalidate();

        //jTable1.setModel(recycle());
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();
        jTable1.clearSelection();
        jTable1.setModel(getdata());


    }//GEN-LAST:event_search_btnActionPerformed

    private void recycle_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recycle_btnActionPerformed
        // TODO add your handling code here:
        Sql s = new Sql();

        Materials_combox.removeAllItems();
        s.Select_MaterialItem(Materials_combox);

        item_combox.removeAllItems();
        s.loadcombo(item_combox);

    }//GEN-LAST:event_recycle_btnActionPerformed

    private void outputExcel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputExcel_btnActionPerformed
        try {
            // TODO add your handling code here:
            writeExcel();

        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_outputExcel_btnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            int mType = JOptionPane.INFORMATION_MESSAGE;
            int msg = JOptionPane.showConfirmDialog(null, "確定要清除本月資料嗎？", "確認",
                    JOptionPane.OK_CANCEL_OPTION, mType);
            System.out.println(msg);

            switch (msg) {
                case 0:
                    new Excel().removeSheet();
                    new WareHouse_Test().remove(jMenu1);
                    break;
                case 2:
                    System.out.println("Cancel");
                    break;
                case -1:
                    System.out.println("Close");
                    break;
            }

        } catch (IOException ex) {
            Logger.getLogger(WareHouse_Test.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menu_addLargeProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_addLargeProjectActionPerformed
        // TODO add your handling code here:
        addLargeProject addType = new addLargeProject();
        addType.setVisible(true);
        addType.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menu_addLargeProjectActionPerformed

    private void menu_addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_addItemActionPerformed
        // TODO add your handling code here:
        addItem addItem = new addItem();
        addItem.setVisible(true);
        addItem.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_menu_addItemActionPerformed

    private void menu_addMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_addMaterialActionPerformed
        // TODO add your handling code here:
        addMaterial addMaterial = new addMaterial();
        addMaterial.setVisible(true);
        addMaterial.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menu_addMaterialActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        importProduct ip = new importProduct();
        ip.setVisible(true);
        ip.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        exportProduct ep = new exportProduct();
        ep.setVisible(true);
        ep.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
                
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        searchPage search = new searchPage();
        search.setVisible(true);
        search.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        search.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        homePage home = new homePage();
        home.setVisible(true);
        home.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WareHouse_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WareHouse_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WareHouse_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WareHouse_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WareHouse_Test wh = new WareHouse_Test();
                wh.setVisible(true);

            }

        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Bigitem_combox;
    private javax.swing.JLabel Label2;
    private javax.swing.JComboBox<String> Materials_combox;
    private javax.swing.JMenu Menu;
    private javax.swing.JTextField company_TFile;
    private javax.swing.JComboBox<String> department_combox;
    private javax.swing.JTextField in_quantity_TFile;
    private javax.swing.JSpinner in_time_spin;
    private javax.swing.JButton in_total_btn;
    private javax.swing.JComboBox<String> in_type_combox;
    private javax.swing.JComboBox<String> item_combox;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem menu_addItem;
    private javax.swing.JMenuItem menu_addLargeProject;
    private javax.swing.JMenuItem menu_addMaterial;
    private javax.swing.JTextField money_TFile;
    private javax.swing.JTextField out_quantity_TFile;
    private javax.swing.JSpinner out_time_spin;
    private javax.swing.JButton out_total_btn;
    private javax.swing.JComboBox<String> out_type_combox;
    private javax.swing.JButton outputExcel_btn;
    private javax.swing.JButton recycle_btn;
    private javax.swing.JButton search_btn;
    private javax.swing.JLabel test;
    // End of variables declaration//GEN-END:variables
}
