/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package page;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import warehouse_test.Sql;

/**
 *
 * @author haven
 */
public class exportProduct extends javax.swing.JFrame {

    /**
     * Creates new form exportProduct
     */
    public exportProduct() {
        initComponents();
        
        Sql s = new Sql();

        s.Select_MaterialItem(Materials_combox);
        s.loadcombo(item_combox);
        s.Select_BigItem(Bigitem_combox);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        company_TFile = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        out_quantity_TFile = new javax.swing.JTextField();
        out_type_combox = new javax.swing.JComboBox<>();
        out_time_spin = new javax.swing.JSpinner();
        item_combox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        Bigitem_combox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Materials_combox = new javax.swing.JComboBox<>();
        out_total_btn = new javax.swing.JButton();
        department_combox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cancel_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel12.setText("出貨日期時間：");

        jLabel14.setText("廠　商：");

        jLabel16.setText("出貨數量：");

        out_type_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "箱", "盒", "個", "公斤", "斤", "公克" }));

        out_time_spin.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));

        item_combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_comboxActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("分　類：");

        Bigitem_combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bigitem_comboxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("大項目：");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("物　料:");

        out_total_btn.setText("出　貨");
        out_total_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                out_total_btnActionPerformed(evt);
            }
        });

        department_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. 吧檯", "2. 外場", "3. 廚房", "4. 甜點" }));

        jLabel13.setText("部　門：");

        cancel_btn.setText("取消");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6))
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(out_quantity_TFile)
                            .addComponent(Bigitem_combox, 0, 106, Short.MAX_VALUE)
                            .addComponent(department_combox, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(company_TFile, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(out_type_combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                        .addComponent(item_combox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel8)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(out_total_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Materials_combox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(out_time_spin, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(item_combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(Bigitem_combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(Materials_combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(out_quantity_TFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(out_type_combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(company_TFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(department_combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(out_time_spin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(out_total_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancel_btn)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item_comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_comboxActionPerformed
        // TODO add your handling code here:
        item_combox = (JComboBox<String>) evt.getSource();
        Object selected = item_combox.getSelectedIndex();
        String test = item_combox.getItemAt((int) selected);
        String result[] = test.split(".  ");

        System.out.println(result[0]);

        Sql s = new Sql();
        int type = Integer.valueOf(result[0]);

        //        type++;

        s.SelectCheck_Material_type(Materials_combox, type);

    }//GEN-LAST:event_item_comboxActionPerformed

    private void Bigitem_comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bigitem_comboxActionPerformed
        // TODO add your handling code here:
        Bigitem_combox = (JComboBox<String>) evt.getSource();
        Object selected = Bigitem_combox.getSelectedIndex();
        String test = Bigitem_combox.getItemAt((int) selected);
        String result[] = test.split(".  ");

        Sql s = new Sql();
        int type = Integer.valueOf(result[0]);
        //        type++;
        //重點
        //        s.SelectCheck_Item_type(item_combox, type);
    }//GEN-LAST:event_Bigitem_comboxActionPerformed

    private void out_total_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_out_total_btnActionPerformed
        // TODO add your handling code here:
        try {
            String no = Materials_combox.getSelectedItem().toString();
            //int money = Integer.parseInt(money_TFile.getText());
            int out_quantity = Integer.parseInt(out_quantity_TFile.getText());
            String out_type = out_type_combox.getSelectedItem().toString();
            String time = out_time_spin.getValue().toString();
            String department = department_combox.getSelectedItem().toString();
            String company = company_TFile.getText();

            Sql s = new Sql();
            s.insert_outTotal(no, out_quantity, out_type, time, department, company);
//            test.setText(no + " " + out_quantity + " " + out_type + " " + time + " " + department + " " + company);

            //clear
            out_quantity_TFile.setText("");
            company_TFile.setText("");
            
            //close
            dispose();

            // TODO add your handling code here:
            //jTable1.invalidate();
            //jTable1.setModel(recycle());
//            DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
//            dm.getDataVector().removeAllElements();
//            dm.fireTableDataChanged();
//            jTable1.clearSelection();
//            jTable1.setModel(getdata());
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null, "有資料未輸入！", "出貨錯誤",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "有資料未輸入！", "出貨錯誤",
                JOptionPane.DEFAULT_OPTION,
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_out_total_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancel_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exportProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exportProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exportProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exportProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exportProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Bigitem_combox;
    private javax.swing.JComboBox<String> Materials_combox;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JTextField company_TFile;
    private javax.swing.JComboBox<String> department_combox;
    private javax.swing.JComboBox<String> item_combox;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField out_quantity_TFile;
    private javax.swing.JSpinner out_time_spin;
    private javax.swing.JButton out_total_btn;
    private javax.swing.JComboBox<String> out_type_combox;
    // End of variables declaration//GEN-END:variables
}
